openapi: 3.0.0
info:
  title: Barberia
  version: 1.0.0
servers:
  - url: http://{{url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
  schemas:
    
tags:
  - name: Auth
  - name: Users
  - name: Turnos
  - name: Reviews
  - name: Servicios barbero
  - name: Productos
paths:
  /
